### ISSUE TITLE
Bot is replying to wrong args

### ISSUE THREAD

**Issue by kcplayz** [iColtz/Poll-Bot#3]
So basically when i run the command the bot only replies with "You need to specify a poll title" even after specifying it. I am sharing my code and a screenshot what it replied it https://hasteb.in/uqepabek.js. i even tried changing the args still i get the error

![image](https://user-images.githubusercontent.com/66863823/97435649-b6c98f80-1946-11eb-897c-f1a91f3bc9fd.png)

**Comment by iColtz** [comment]
@kcplayz You can see in the README.md or in the help command the format of the command should be.
`eb!poll {Test} [Option 1] [Option 2] [Option 3]` Note: There can be up to 20 options.
however if you want to do a timed poll the command format is
`eb!poll {Test} {Time} [Option 1] [Option 2] [Option 3]`
