### ISSUE TITLE
Timed poll is not working

### ISSUE THREAD

**Issue by kcplayz** [iColtz/Poll-Bot#4]
![image](https://user-images.githubusercontent.com/66863823/97715333-422e5680-1ae8-11eb-9236-829d23061898.png)
The bot is adding thee wrong args to the title and the timed poll is not working

**Comment by iColtz** [comment]
@kcplayz Updated the regex to match the title to use a lazy quantifier. It should work fine now. The timed polls are checked every 30 seconds for expired polls in a regular interval in the ready event so it wont end exactly on the 5 second mark.
